name: $(major).$(minor).$(Rev:r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - BicepTemplates/Templates*

pool:
  vmImage: 'windows-latest'

variables:
  location: 'centralus'
  major: 1
  minor: 0

stages:

  - stage: build
    displayName: Build
    jobs:
      - job: Build
        pool:
          vmImage: windows-latest
        steps:
          - template: ./build-steps.yml

  - stage: "publish_dev"
    displayName: Publish Dev
    dependsOn: ["build"]
    condition: succeeded()
    variables:
      - template: ../Variables/dev-variables.yml
    jobs:
      - deployment: 'dev'
        displayName: 'Publish'
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./deployment-steps.yml
                  parameters:
                    azureSubscriptionServiceConnection: ${{ variables.azureSubscription }}
                
  - stage: "publish_prd"
    displayName: Publish Production
    dependsOn: ["publish_dev"]
    condition: succeeded()
    variables:
      - template: ../Variables/dev-variables.yml
    jobs:
      - deployment: 'prd'
        displayName: 'Publish'
        environment: 'prd'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./deployment-steps.yml
                  parameters:
                    azureSubscriptionServiceConnection: ${{ variables.azureSubscription }}
                    
