name: $(major).$(minor).$(Rev:r)

trigger:
  branches:
    include:
      - main
      
  paths:
    include:
      - ARMTemplates/*
pool:
  vmImage: 'windows-latest'

variables:
  location: 'centralus'

stages:

  - stage: build
    displayName: Build
    jobs:
      - job: Build
        pool:
          vmImage: windows-latest
        steps:
          - template: ./build-steps.yml

                
  - stage: "release_prd"
    displayName: Release Production
    dependsOn: ["build"]
    condition: succeeded()
    jobs:
      - deployment: 'prd'
        displayName: 'PRD'
        pool:
          vmImage: windows-latest
        environment: 'prd'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./deployment-steps.yml
                  parameters:
                    azureSubscriptionServiceConnection: AzDevOps-Prd-ServiceConnection
                    
