steps:

- task: DownloadPipelineArtifact@2
  inputs:
    artifact: 'Templates'
    targetPath: $(Build.SourcesDirectory)/bin/Templates
    
- task: UniversalPackages@0
  displayName: 'Publish to Central Feed'
  inputs:
    command: publish
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    vstsFeedPublish: 'LefewareSolutions/lws-dev-infra-feed'
    vstsFeedPackagePublish: Templates
    versionOption: custom
    versionPublish: $(Build.BuildNumber)


            #  vstsFeedPublish: '408eb3c6-5977-45d5-943a-04c14a905ae5/9c0c3113-7f72-4174-8b9e-78ed7a358041'