parameters:
- name: 'azureSubscription'
  type: string
  default: false

steps:
  - checkout: self

  - task: AzureCLI@2
    displayName: 'Deploy Bicep Template'
    inputs:
      azureSubscription: ${{parameters.azureSubscription}}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $resourceGroupName="lws-eus-$(environment)-networking-rg"
        
        az deployment group create  `
          --mode Incremental `
          --resource-group $resourceGroupName `
          --output yamlc `
          --template-file $(Build.SourcesDirectory)\Deployments\Networking\main.bicep `
          --parameters $(Build.SourcesDirectory)\Deployments\Networking\Parameters\parameters.$(environment).json
